### ISSUE TITLE
Bug? Clicking on "Latest Change" is triggering notifications

### ISSUE THREAD

**Issue by dmil** [themarshallproject/klaxon#107]
I decided to try out klaxon and somehow got it into some strange buggy state where I have watchers that are updating but the feed remains blank.

I get emails showing me the full change (see below)
https://www.evernote.com/shard/s150/sh/e0fbf50f-4275-446c-9992-6f746e101120/c7ae03b13bd960e1/res/cb4081ca-1169-4186-bdda-80bc627383e4/skitch.png?resizeSmall&width=832

but the feed is still blank in the GUI. Also, every time I click "latest change" it just triggers the notifications - sends an email and messages me on slack and then redirects me to the 500 error page. (see gif below)

https://i.gyazo.com/cab36904186786485a34360d105e8718.mp4

Here are some of the things I've done since deploying Klaxon on Heroku:
- Enabled slack notifications
- Create a few watchers
- Delete and re-create watcher for this site: http://tycho.usno.navy.mil/cgi-bin/timer.pl
- Enable SQS integration (not sure if I did this successfully or not yet)

I noticed the issue after deleting and recreating a watcher and enabling an SQS integration, so I'm not sure which of the two caused this (or if it was something else). I had just deployed Klaxon and was playing around with it, so I'm not actually using it for anything yet, but just wanted to point this out in case its not a known issue.

**Comment by dmil** [comment]
Deleting the bad SQS integration fixes this.

This is from the Heroku Logs
```
2017-03-20T22:06:35.389859+00:00 app[web.1]:    (10.8ms)  ROLLBACK
2017-03-20T22:06:35.396416+00:00 app[web.1]: Completed 500 Internal Server Error in 3281ms (ActiveRecord: 92.6ms)
2017-03-20T22:06:35.402903+00:00 app[web.1]:
2017-03-20T22:06:35.402907+00:00 app[web.1]: URI::InvalidURIError (bad URI(is not URI?): https://sqs.us-east-1.amazonaws.com/XXXXXXXXX/test-klaxon	):
2017-03-20T22:06:35.402908+00:00 app[web.1]:   app/lib/sqs_notification.rb:13:in `perform'
2017-03-20T22:06:35.402909+00:00 app[web.1]:   app/models/sqs_integration.rb:31:in `send_notification'
2017-03-20T22:06:35.402909+00:00 app[web.1]:   app/models/change.rb:31:in `block in send_notifications'
2017-03-20T22:06:35.402910+00:00 app[web.1]:   app/models/change.rb:31:in `send_notifications'
2017-03-20T22:06:35.402910+00:00 app[web.1]:   app/models/page.rb:80:in `latest_change'
2017-03-20T22:06:35.402911+00:00 app[web.1]:   app/controllers/pages_controller.rb:6:in `latest_change'
2017-03-20T22:06:35.402912+00:00 app[web.1]:
2017-03-20T22:06:35.402912+00:00 app[web.1]:
2017-03-20T22:06:37.219358+00:00 app[web.1]:    (2.0ms)  ROLLBACK
2017-03-20T22:06:37.221872+00:00 app[web.1]: Completed 500 Internal Server Error in 3208ms (ActiveRecord: 61.8ms)
2017-03-20T22:06:37.225209+00:00 app[web.1]:
2017-03-20T22:06:37.225211+00:00 app[web.1]: URI::InvalidURIError (bad URI(is not URI?): https://sqs.us-east-1.amazonaws.com/XXXXXXXXX/test-klaxon	):
2017-03-20T22:06:37.225212+00:00 app[web.1]:   app/lib/sqs_notification.rb:13:in `perform'
2017-03-20T22:06:37.225213+00:00 app[web.1]:   app/models/sqs_integration.rb:31:in `send_notification'
2017-03-20T22:06:37.225214+00:00 app[web.1]:   app/models/change.rb:31:in `block in send_notifications'
2017-03-20T22:06:37.225214+00:00 app[web.1]:   app/models/change.rb:31:in `send_notifications'
2017-03-20T22:06:37.225215+00:00 app[web.1]:   app/models/page.rb:80:in `latest_change'
2017-03-20T22:06:37.225215+00:00 app[web.1]:   app/controllers/pages_controller.rb:6:in `latest_change'
2017-03-20T22:06:37.225216+00:00 app[web.1]:
```

**Comment by tommeagher** [comment]
Thanks for reporting this Dhrumil. It's a new one on us. After you deleted the SQS integration, did the alerts start appearing in your feed?

**Comment by dmil** [comment]
yes, deleting the SQS integration fixed the issue

**Comment by tommeagher** [comment]
Fascinating. We'll dig into it. Thanks for flagging this!

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 7 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
