### ISSUE TITLE
Unable to deploy to Heroku

### ISSUE THREAD

**Issue by webster** [themarshallproject/klaxon#120]
Deploying to Heroku results in an error: "Item could not be created: Unknown Error. Please contact support." - No further information was provided; no debug/error log generated. All required fields were filled.

<img width="279" alt="screen shot 2017-05-19 at 1 07 43 pm" src="https://cloud.githubusercontent.com/assets/166752/26260883/aeaa9016-3c94-11e7-9014-1caf167c38da.png">

Using Chrome 58 on macOS 10.12.4

**Comment by GabeIsman** [comment]
Hey @webster, just did some digging into this and it seems like this is an issue with the Heroku deploy button UI. For me, I saw the exact same error, but when I navigated to the Heroku dashboard where it lists my apps, the test instance was happily spinning up (and completing successfully). I have no idea why that error is appearing, but it doesn't seem to actually be affecting deployment. Let me know if it's otherwise!

**Comment by GabeIsman** [comment]
Just tested this again, and did not encounter the problem. Transient bug on Heroku's end, IMO.

**Comment by bbhoss** [comment]
Seeing this again: 
![image](https://user-images.githubusercontent.com/7044/36169811-535c5a08-10cb-11e8-9b49-38ff1f86f777.png)

**Comment by GabeIsman** [comment]
Hmm, that's not a super useful error message @bbhoss. When I tried it just now I did get a different error message though! I'm working on fixing that one, and maybe it will be related.

**Comment by bbhoss** [comment]
Thanks, wish I had more. I tried clearing out my account, updating credit card, etc, and nothing seemed to help.

**Comment by bbhoss** [comment]
Walked away and came back, and it started working better. Now I'm getting another exception, likely the one you're speaking of. Maybe this is just a transient heroku issue, though this is the first time I've experienced this. Sharing the new error in case it's helpful

```
-----> Rake app detected
rake aborted!
NoMethodError: undefined method `web_console' for #<Rails::Application::Configuration:0x00000005963ea8>
Did you mean?  console
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/railtie/configuration.rb:95:in `method_missing'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/config/environments/development.rb:41:in `block in <top (required)>'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `instance_eval'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/railtie.rb:210:in `configure'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/config/environments/development.rb:1:in `<top (required)>'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `each'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/engine.rb:597:in `block in <class:Engine>'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `instance_exec'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:30:in `run'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:55:in `block in run_initializers'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `each'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:44:in `tsort_each_child'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/initializable.rb:54:in `run_initializers'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:352:in `initialize!'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/config/environment.rb:5:in `<top (required)>'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:328:in `require_environment!'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/railties-4.2.10/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/tmp/build_6ecfedffce95cf7a18bc11ad2e06dd54/themarshallproject-klaxon-c2d43ef/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
 !     Push rejected, failed to compile Rake app.
 !     Push failed
```

**Comment by GabeIsman** [comment]
Yep! That's the one. Merging into master now.

**Comment by GabeIsman** [comment]
Should be good to go now @bbhoss

**Comment by bbhoss** [comment]
Working now, thanks again
