### ISSUE TITLE
Error 500 

### ISSUE THREAD

**Issue by fdaudens** [themarshallproject/klaxon#149]
Hi,
Maybe you can help me. Suddenly, we have an error 500 with Klaxon, and I'm not sure where to fix the problem. The log returns this message:

```
2018-04-27T20:47:50.558009+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2018-04-27T20:47:50.558010+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2018-04-27T20:47:50.558012+00:00 app[web.1]:                WHERE a.attrelid = '"app_settings"'::regclass
2018-04-27T20:47:50.558013+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2018-04-27T20:47:50.558015+00:00 app[web.1]:                ORDER BY a.attnum
2018-04-27T20:47:50.558016+00:00 app[web.1]: ):
2018-04-27T20:47:50.558018+00:00 app[web.1]:   app/models/app_setting.rb:8:in `default_host_exists?'
2018-04-27T20:47:50.558020+00:00 app[web.1]:   app/controllers/application_controller.rb:16:in `set_default_host'
2018-04-27T20:47:50.558021+00:00 app[web.1]: 
2018-04-27T20:47:50.558022+00:00 app[web.1]: 
```

Has anyone had the same problem? 

Thanks,

Florent

**Comment by tommeagher** [comment]
@fdaudens thanks for flagging this. We haven't seen it. We'll see if @GabeIsman has any advice on debugging this. Do you happen to know which version of Klaxon you're running?

**Comment by fdaudens** [comment]
@tommeagher Thanks for your answer. Not sure of the version, but I've installed it on March 2017 and didn't updated it since.

**Comment by GabeIsman** [comment]
Hey @fdaudens, sorry you're running into this issue. I don't think I've seen this before, but it's a little hard to tell because it looks like the logs you've pasted don't include the full error message. Can you send a little more context from the logs?

**Comment by fdaudens** [comment]
Hey @GabeIsman, sorry, didn't realize it was not complete. Unfortunately, Heroku only allows to retrieve logs for one week, and I've installed the latest Klaxon version since. The database was rebooted, but everything works fine. Will copy the logs if it happens again.

**Comment by tommeagher** [comment]
@fdaudens we'll close the issue for now, but if it happens again, please re-open it and share the full logs so we can try to get to the bottom of it.

Thanks!
