### ISSUE TITLE
Deleting active Slack integration causes repeat email notifications 

### ISSUE THREAD

**Issue by myersjustinc** [themarshallproject/klaxon#92]
We've found in our (non-Heroku) installation at the AP that the `check:all` task errors out for a page under the following conditions:

*   The page was set to send notifications to a Slack integration.
*   The Slack integration was deleted altogether, but that integration was not first unchecked in the page's individual configuration.

This error occurs in such a way that email users still are notified, but that fact somehow isn't recorded—so those users get identical notifications on every subsequent run of `check:all`.

Steps to reproduce:

## Environment setup ##

*   Clone the `themarshallproject/klaxon` repo; I was on commit `498cdb507ff14ef69d302a7d98817447c535fc95`.

*   Run `bundle install`.

*   Ensure `SECRET_KEY_BASE` and `ADMIN_EMAILS` environment variables are set.

*   Run `bundle exec rake db:drop` if you have an existing `klaxon_development` database.

*   Run `bundle exec rake db:setup`.

*   Run `bundle exec rake users:create_admin`.

*   Run `bundle exec rackup`.

## Page setup ##

*   Log in to Klaxon—should be at <http://localhost:9292/> by default.

*   Create a Slack integration.

*   Use the bookmarklet to start watching a page (allowing unsafe scripts if necessary). I've observed this bug in two places so far:

    *   <https://www.whitehouse.gov/blog>, selector `div.view-content`
    *   <https://status.github.com/>, selector `div#graph_data`

*   Configure this page to send notifications to the Slack integration and to your admin user's email address.

## Notifications ##

*   Run `bundle exec rake check:all` in order to capture an initial snapshot.

*   Wait for the page to change.

*   Run `check:all` again. You should get a change notification.

*   From the Integrations settings page (`/integrations`), edit the Slack integration and delete with the `Delete? It's Permanent.` button.

*   Wait for the page to change.

*   Run `check:all` again. You should get another notification email and the error shown under `Error details` below.

*   Before the page changes again, run `check:all` again. You should get the same error, and even though there was no additional change, any configured email recipient should receive a repeat notification.

## Error details ##

```
NoMethodError: undefined method `send_notification' for nil:NilClass
/Users/idguser/misc/klaxon/app/models/subscription.rb:9:in `send_notification'
/Users/idguser/misc/klaxon/app/models/change.rb:26:in `block in send_notifications'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:46:in `map'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:46:in `map'
/Users/idguser/misc/klaxon/app/models/change.rb:25:in `send_notifications'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:506:in `block in call'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:506:in `each'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:506:in `call'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/callbacks.rb:306:in `_create_record'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/timestamp.rb:57:in `_create_record'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:504:in `create_or_update'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/callbacks.rb:302:in `create_or_update'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:120:in `save'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/validations.rb:37:in `save'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:286:in `block in save'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/transactions.rb:285:in `save'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/persistence.rb:34:in `create'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:143:in `block in create'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:302:in `scoping'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:143:in `create'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:155:in `first_or_create'
/Users/idguser/misc/klaxon/app/models/change.rb:43:in `block in check'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:46:in `each'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/delegation.rb:46:in `each'
/Users/idguser/misc/klaxon/app/models/change.rb:35:in `check'
/Users/idguser/misc/klaxon/lib/tasks/check.rake:8:in `block (2 levels) in <top (required)>'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/Users/idguser/.rvm/gems/ruby-2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/Users/idguser/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `load'
/Users/idguser/.rvm/gems/ruby-2.3.0/bin/bundle:23:in `<main>'
```

**Comment by tommeagher** [comment]
@myersjustinc Hey Justin, thanks for this very thorough bug report. We'll dig into it.

**Comment by GabeIsman** [comment]
Thanks for all this detail @myersjustinc! I've just pushed up https://github.com/themarshallproject/klaxon/commit/8222f6b20cf20db1511887853174a20fd75f33fe which should fix this. It'll be included in a point release soon!

**Comment by myersjustinc** [comment]
Many thanks!
